/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */
import type { ChallengeAssignment } from './2023_generated_interfaces/challenge/challengeAssignment';
import type { Category } from './2023_generated_interfaces/category';
import type { ChallengeEventSerializer } from './2023_generated_interfaces/challenge/challengeEventSerializer';
import type { Sponsor } from './2023_generated_interfaces/event/sponsor';
import type { Tag } from './2023_generated_interfaces/tag';
import type { DifficultyProp } from '../components/general/DifficultyChip';

export interface Challenge {
  readonly active_assignments: ChallengeAssignment[];
  readonly author: string;
  readonly bookmarked: boolean;
  category: Category;
  readonly difficulty: DifficultyProp;
  readonly description: string;
  readonly errata: string;
  event: ChallengeEventSerializer;
  /** The amount of points this challenge is worth when solved in its event. */
  readonly event_points: number;
  readonly flag: string;
  /** The amount of points this challenge is worth when solved in the gym. */
  readonly gym_points: number;
  readonly hints: string[];
  readonly id: number;
  /** Whether this challenge should be accessible in the gym after its associated event ends. */
  readonly include_in_gym: boolean;
  readonly name: string;
  rating_percentage: number;
  readonly solved_by_team: boolean;
  readonly solved_by_user: boolean;
  sponsor: Sponsor;
  tags: Tag[];
  /** Whether this challenge is temporarily down for maintenance. If set, instances will not be available. Does not affect event or gym scoring. */
  readonly under_maintenance: boolean;
  users_attempted: number;
  users_attempted_during_event: number;
  users_solved: number;
  users_solved_during_event: number;
}

export function isChallenge(obj: any): obj is Challenge {
    return (
        typeof obj === 'object' &&
        obj !== null &&
        typeof obj.active_assignments === "object" &&
        typeof obj.author === "string" &&
        typeof obj.bookmarked === "boolean" &&
        typeof obj.category === "object" &&
        typeof obj.errata === "string" &&
        typeof obj.difficulty === "object" &&
        typeof obj.event === "object" &&
        typeof obj.event_points === "number" &&
        typeof obj.gym_points === "number" &&
        typeof obj.id === 'number' &&
        typeof obj.include_in_gym == "boolean" &&
        typeof obj.name === 'string' &&
        typeof obj.rating_percentage === "number" &&
        typeof obj.solved_by_team === "boolean" &&
        typeof obj.solved_by_user === "boolean" &&
        typeof obj.sponsor === "object" &&
        typeof obj.tags === "object" && 
        typeof obj.under_maintenance === "boolean" &&
        typeof obj.users_attempted === "number" &&
        typeof obj.users_attempted_during_event === "number" &&
        typeof obj.users_solved === "number" &&
        typeof obj.users_solved_during_event === "number"
    );
}