/**
 * Generated by orval v6.20.0 🍺 - Edited to add the tags property
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */
import type { Sponsor } from './2023_generated_interfaces/event/sponsor';
import type { EventTag } from './eventTag';

export interface Event {
  description?: string;
  /** The time at which event submissions close. Challenges will become accessible in the Gym unless explicitly excluded. Cannot be changed once the event has ended. */
  end_time: string;
  game?: number | null;
  readonly has_ended: boolean;
  readonly has_opened: boolean;
  readonly has_public_scoreboards: boolean;
  readonly has_started: boolean;
  readonly id: number;
  readonly is_password_protected: boolean;
  logo?: string | null;
  /** Must be greater than 1 to enable team functionality. Cannot be decreased once set. */
  max_team_size?: number;
  name: string;
  /** The time at which players can register and form teams. Cannot be changed once the event has opened. */
  opening_time: string;
  readonly registered: boolean;
  readonly sponsor: Sponsor;
  /** The time at which challenge descriptions and submissions will become available to players. Cannot be changed once the event has started. */
  start_time: string;
  readonly submission_context: number;
  summary?: string;
  /** The tags associated with this challenge. */
  tags: EventTag[];
}