/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */

export interface AssignmentResultChallenge {
  readonly id: number;
  readonly name: string;
  readonly points: number;
  readonly solve_time: string | null;
  readonly solved_by_due_date: boolean;
  readonly suspicious_submissions: string[];
}