/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */

export interface Score {
  readonly linkable: boolean;
  readonly name: string;
  readonly score: number;
  readonly scorer_id: number;
  /** Will be one of `user` or `team`. */
  readonly scorer_type: string;
}