/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */

export interface TeamDisqualificationInfo {
  readonly disqualified: boolean;
  readonly reason: string;
}