/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for public information about a team member.

Intended for nesting into PublicTeamSerializers.
 */
export interface PublicTeamMember {
  readonly is_active: boolean;
  /** Return whether the associated user's profile is set to private mode.

This can be used to avoid generating links to private user profiles without
checking the effective username. */
  readonly is_private: boolean;
  readonly team_leader: boolean;
  /** Return this user's contribution to the overall team score. */
  readonly team_score_contribution: number;
  user_id: number;
  readonly username: string;
}