/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */
import type { NestedEventInformation } from '../event/nestedEventInformation';
import type { PublicTeamMember } from './publicTeamMember';

/**
 * Serializer for public team information (/teams/:id/).

Pending members are not included.
 */
export interface PublicTeam {
  event: NestedEventInformation;
  readonly id: number;
  readonly members: PublicTeamMember[];
  readonly name: string;
  team_score: number;
}