/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */

export type TeamMemberScoreboardsRevokedOnApprovalItem = {
  id: number;
  name: string;
};