/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */
import type { TeamDisqualificationInfo } from './teamDisqualificationInfo';

export interface Team {
  readonly disqualification_info: TeamDisqualificationInfo;
  readonly id: number;
  readonly invite_code: string;
  name: string;
  /** This team's score for the associated event. */
  readonly score: number;
}