/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */
import type { TeamMemberScoreboardsRevokedOnApprovalItem } from './teamMemberScoreboardsRevokedOnApprovalItem';

/**
 * Used to serialize team members.
 */
export interface TeamMember {
  readonly id: number;
  /** Returns the current team eligibilities that will be lost if this member joins. */
  readonly scoreboards_revoked_on_approval: TeamMemberScoreboardsRevokedOnApprovalItem[];
  readonly team_leader: boolean;
  readonly team_membership_pending: boolean;
  readonly username: string;
}