/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Provides minimal information about an event (essentially only its name).

This is intended for nesting into public profile/team serializers, or in other
places where the authenticated-user-specific elements of EventSerializer are not
applicable or available (i.e. outside of EventViewSet).
 */
export interface NestedEventInformation {
  readonly id: number;
  readonly name: string;
}