/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */

export interface Classroom {
  readonly id: number;
  /** Whether to include classroom leaders in scoring. */
  include_leaders_in_scoring?: boolean;
  readonly invite_code: string;
  /** Whether the user is a leader of this classroom. */
  readonly leader: boolean;
  name: string;
  /** Whether the user's membership in this classroom is pending. */
  readonly pending: boolean;
}