/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */
import type { ClassroomMember } from './classroomMember';

export interface PaginatedClassroomMemberList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: ClassroomMember[];
}