/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */
import type { Classroom } from './classroom';

export interface PaginatedClassroomList {
  count?: number;
  next?: string | null;
  previous?: string | null;
  results?: Classroom[];
}