/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 * EDITED FOR USE WITH LEARNING PATHS
 */

export interface Resource {
    description: string;
    readonly id: number;
    link: string;
    name: string;
    rating_percentage: number;
    type: "Primer" | "Video";
}

export function isResource(obj: any): obj is Resource {
    return (
        typeof obj === 'object' &&
        obj !== null &&
        typeof obj.description === "string" &&
        typeof obj.id === "number" &&
        typeof obj.link === "string" &&
        typeof obj.name === "string" &&
        typeof obj.rating_percentage === "number" &&
        typeof obj.type === "string"
    );
}