/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */

import type { AssignmentClassroom } from './assignmentClassroom';
import type { AssignmentResultChallenge } from './assignmentResultChallenge';

export interface AssignmentResponse {
  readonly active: boolean;
  readonly challenges: AssignmentResultChallenge[];
  readonly classroom: AssignmentClassroom;
  readonly created: boolean;
  readonly due_date: string;
  readonly id: number;
  readonly name: string;
}