/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `NA` - None
 * `GZ` - Gzip
 * `BR` - Brotli
 */
export type CompressionEnum = (typeof CompressionEnum)[keyof typeof CompressionEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompressionEnum = {
  NA: 'NA',
  GZ: 'GZ',
  BR: 'BR',
} as const;