/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Configuration values to expose to the game. Note that the contents of this field are publicly accessible.
 */
export type GameSettings = { [key: string]: unknown };