/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * picoCTF platform API
 * OpenAPI spec version: 1.0.0
 */
import type { CompressionEnum } from './compressionEnum';
import type { GameSettings } from './gameSettings';

export interface Game {
  build_name: string;
  /** e.g. https://cdn.example.com/Build */
  build_url: string;
  compression?: CompressionEnum;
  description?: string;
  /** Whether to display a leaderboard for this game. */
  display_leaderboard?: boolean;
  readonly id: number;
  launch_image?: string | null;
  name: string;
  /** Configuration values to expose to the game. Note that the contents of this field are publicly accessible. */
  settings?: GameSettings;
}

export function isGame(obj: any): obj is Game {
    return (
        typeof obj === 'object' &&
        obj !== null &&
        typeof obj.build_name === "string" &&
        typeof obj.build_url === "string" &&
        (typeof obj.compression === "object" || 
        typeof obj.compression === "undefined") &&
        (typeof obj.descripiton === "string" ||
        typeof obj.descripiton === "undefined") &&
        (typeof obj.display_leaderboard === "string" ||
        typeof obj.display_leaderboard === "undefined") &&
        typeof obj.id === "number" &&
        (typeof obj.launch_image === "string" ||
        typeof obj.launch_image === "undefined") &&
        typeof obj.name === "string" &&
        (typeof obj.settings === "object" ||
        typeof obj.settings === "undefined")
    );
}